version: '3.7'

services:
  mongo-db:
    container_name: crawler_db
    image: mongo:4.0
    ports:
        - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
  crawler-api:
    container_name: crawler_api
    image: rienelmot24/diploma-crawler-api
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: admin
      DB_PASSWORD: admin
    depends_on: 
      - mongo-db
